[tool.black]
    line-length = 99
    target-version = ['py38']
    include = '\.py$'

[tool.isort]
profile = 'black'

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "88"