name: Auto Labeler - PRs
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      
permissions:
  pull-requests: write

jobs:
  label_pull_requests:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Type Label
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
